version: '1'
services:
  api:
    container_name: 'medods-jwt'
    build: '.'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'